force-app/main/default/objects/Conference__c/Conference__c.object-meta.xml
<CustomObject>
    <label>Conference</label>
    <nameField>
        <label>Conference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conference__c/fields/Media_Reference__c.field-meta.xml
<CustomField>
    <fullName>Media_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Media Reference</label>
    <referenceTo>Media__c</referenceTo>
    <relationshipLabel>Conferences</relationshipLabel>
    <relationshipName>Conferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Media__c/Media__c.object-meta.xml
<CustomObject>
    <description>A custom object that stores AWS Media file reference in Salesforce</description>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Media__c/fields/Media_URL__c.field-meta.xml
<CustomField>
    <fullName>Media_URL__c</fullName>
    <description>URL to download the media</description>
    <label>Media URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/AudioFileUploader.cls
public with sharing class AudioFileUploader {
    @AuraEnabled
    public static List<Id> createConference(String title, Id fileId) {
        List<Id> ids = new List<Id>();
        try {

        ContentVersion cv = [SELECT ContentDocumentId, Title, FileExtension, VersionData FROM ContentVersion WHERE ContentDocumentId = :fileId LIMIT 1];

        // Step 2: Create the Media__c record
        Media__c media = new Media__c();
        media.Name = cv.Title + '.' + cv.FileExtension;
        media.Media_URL__c = '/services/data/v61.0/sobjects/ContentVersion/' + cv.Id + '/VersionData';
        media.Content_Document_Id__c = cv.ContentDocumentId;
        media.Media_Type__c = cv.FileExtension;
        insert media;
        ids.add(media.Id);

        // Step 3: Create the Conference__c record and link it to the Media__c record
        Conference__c conference = new Conference__c();
        conference.Name = title;
        conference.Media_Reference__c = media.Id;
        insert conference;
        ids.add(conference.Id);

        // Step 4: Add ContentDocumentId to the result to send back to LWC
        ids.add(cv.ContentDocumentId);

        } catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
        }

        // Step 4: Return the ID of the newly created conference
        return ids;
    }
}